### ISSUE TITLE
Object Promise && 500 (Internal server error)

### ISSUE THREAD

**Issue by rumon5h** [adrianhajdin/project_openai_codex#21]
![Screenshot from 2023-01-10 21-00-03](https://user-images.githubusercontent.com/94229744/211587334-8766547c-9c97-4454-a68c-207b20616acc.png)

**Comment by ka7em** [comment]
do the error still exists?

**Comment by branihat** [comment]
> do the error still exists?

yes

**Comment by alexandra0606** [comment]
I have the same issue , is working locally but when I want to deploy it I have error 500 . The API key is the same in Render .

**Comment by rumon5h** [comment]
I think this problem came from Openai. 

@ka7em @Montaser778 @branihat @alexandra0606

**Comment by Maverik0071** [comment]
I have this same issue.  How do we fix this issue?

**Comment by willgoncdev** [comment]
Did it work when it was locally hosted? The key on his project is already expired or out of credits, so you should get your own key, is not expensive, and it will charge you as you use it.  Or if 
you can try to get a trial for OpenAI I think you get a $5 credit.
