### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Tanimou** [adrianhajdin/project_openai_codex#3]
I followed each step, but I always get a server error. Please help

**Comment by Alia2006** [comment]
same to me, it worked local, but get server error after deploy.

**Comment by teejaywurld** [comment]
@Tanimou I would advise you go through the tutorial again but carefully this time around and then watch out for your capital and small letters. They might have been mixed up somewhere. Like in my own case, i misspelled "apiKey" with a small letter "k" and my code was showing error until i figured it out.

I hope this helps

**Comment by Tanimou** [comment]
I already did that teejaywurld. Here's a screeshot of what I get:
![image](https://user-images.githubusercontent.com/91100433/209543378-04f05811-1e8b-4d01-a32f-da6d501b1cad.png)

I think the problem is on the client side

**Comment by teejaywurld** [comment]
@Alia2006 Did you follow the tutorial to the end? 

I believe this issue was addressed there towards the end of the tutorial

**Comment by teejaywurld** [comment]
@Tanimou I would still advise you go over your code again and compare it to the tutorial you watched. 

There must have been a mix up somewhere down the line while writing your code.

**Comment by Alia2006** [comment]
> @Alia2006 Did you follow the tutorial to the end?
> 
> I believe this issue was addressed there towards the end of the tutorial

Yes, I have followed to the end. I guess you are saying the updtae server url part. the deployed server can response the text 'Hello from CodeX!' and when fectch in client code get repsonse with 401 
![image](https://user-images.githubusercontent.com/93459415/209582833-03406f8f-114b-4acc-ac29-15b4fb6cbe8b.png)

**Comment by Tanimou** [comment]
Exactly same for me but with status code 429. It's really weird. Did you fix this Alia? After some research on that, they said that this error occurs because the client sends too many requests in a short time, so the server sends this error to kind of say: "woowooo calm down buddy, you too fast".

**Comment by Tanimou** [comment]
@teejaywurld I forked his repo to try on my side and I still have the same 429 code error. I think now maybe it's the region I don't know

**Comment by crocmons** [comment]
> > @Alia2006 Did you follow the tutorial to the end?
> > I believe this issue was addressed there towards the end of the tutorial
> 
> Yes, I have followed to the end. I guess you are saying the updtae server url part. the deployed server can response the text 'Hello from CodeX!' and when fectch in client code get repsonse with 401 ![image](https://user-images.githubusercontent.com/93459415/209582833-03406f8f-114b-4acc-ac29-15b4fb6cbe8b.png)

I solve the issue of 429 getting an HTTP Error....
you have to sign up with your own email address (not google)  and do phone verification then it will give you the free trial of $18 ..and then the code will perfectly work.

**Comment by crocmons** [comment]
> @teejaywurld I forked his repo to try on my side and I still have the same 429 code error. I think now maybe it's the region I don't know

@Tanimou I solve the issue of 429 getting an HTTP Error....
you have to sign up with your own email address (not google)  and do phone verification then it will give you the free trial of $18 ..and then the code will perfectly work.

**Comment by Tanimou** [comment]
@crocmons I have to sign up where? 😅

**Comment by TidbitsJS** [comment]
> @crocmons I have to sign up where? sweat_smile

Sign up here and get the secret/API key:
https://beta.openai.com/signup

**Comment by RosaMoran** [comment]
@Tanimou if you look this screenshot you have to make a new key then add it to .env and also add it into `render` => `Environment` paste the new key and save it 


![Screenshot from 2022-12-27 13-40-32](https://user-images.githubusercontent.com/78501106/209667872-d83b0a2a-ff6b-4a12-b9c4-be6e0083740e.png)



you are going to get that error because on the openai site they check if you use your key as public then you are not going to be able to use their api, so you have to make a new one and use it where you have been using them. 

In the tutorial there is a point where the gitignore doesn't work, I solved it by deleting the document from my repository and the env to make a push and then add it one more time inside the server with the env and the new key, make the push to add it and that's how it worked for me.

![Screenshot from 2022-12-27 13-33-37](https://user-images.githubusercontent.com/78501106/209667243-b885baf6-3faf-4612-9b0f-e9d7142ace47.png)

**Comment by Tanimou** [comment]
I finally managed to resolve the issue by effectively signing up with my email and also getting a new API key and replacing it in environment variable as well. Thanks @RosaMoran and @ @crocmons 
![image](https://user-images.githubusercontent.com/91100433/209675284-8b7fc223-3f6e-46a2-91cb-9f6d2685de1f.png)

**Comment by crocmons** [comment]
@Tanimou My pleasure.

**Comment by Tanimou** [comment]
Thank also @teejaywurld and @TidbitsJS
