### ISSUE TITLE
render failed

### ISSUE THREAD

**Issue by Skullomanic84** [adrianhajdin/project_openai_codex#4]
Thanks Adrian for the wonderful tutorial. Am having an issue uploading the server files to render. Keep getting an error 

![image](https://user-images.githubusercontent.com/55574810/209454624-4f2be4b1-83d8-40b9-b904-304d9f3fa614.png)

 see image attached. Any assistance or advice

git link: https://github.com/Skullomanic84/codex

**Comment by RosaMoran** [comment]
the path look like if it's wrong
i have my path like this 
`server@1.0.0 server /opt/render/project/src/server`

**Comment by Tanimou** [comment]
seems like bunch of people couldn't get their code working well too. I keep having server side error

**Comment by crocmons** [comment]
> Thanks Adrian for the wonderful tutorial. Am having an issue uploading the server files to render. Keep getting an error
> 
> ![image](https://user-images.githubusercontent.com/55574810/209454624-4f2be4b1-83d8-40b9-b904-304d9f3fa614.png)
> 
> see image attached. Any assistance or advice
> 
> git link: https://github.com/Skullomanic84/codex

I solve the issue of 429 getting Http Error....
you have to sign up with your email and phone verification then it will give you the free trial of $18 ..and then the code will perfectly work

**Comment by crocmons** [comment]
I solve the issue of 429 getting an HTTP Error....
you have to sign up with your own email address (not google)  and do phone verification then it will give you the free trial of $18 ..and then the code will perfectly work.

**Comment by crocmons** [comment]
> Thanks Adrian for the wonderful tutorial. Am having an issue uploading the server files to render. Keep getting an error
> 
> ![image](https://user-images.githubusercontent.com/55574810/209454624-4f2be4b1-83d8-40b9-b904-304d9f3fa614.png)
> 
> see image attached. Any assistance or advice
> 
> git link: https://github.com/Skullomanic84/codex

@Skullomanic84  issue solved -- My code is perfectly working you can check it -- https://chatbot-nine-inky.vercel.app/

**Comment by crocmons** [comment]
@Skullomanic84 @adrianhajdin 
Make sure that your localhost is closed that is not up & running because it conflicts with your API key with the live deployment API key.
then deploy the server to render.com and add also your environment key into the Environment variable
Now Update your fetch URL on the client side by adding your back-end render deploy URL 
then open your terminal and do this thing --
git init
git add .
git commit -m "fetch URL or something you want"
git push

That should be updated,  your GitHub code .
Now go to the vercel select your GitHub repo 
The root directory should be client
then hit deploy
that's all ..
My code is perfectly working on live you can check it -- https://chatbot-nine-inky.vercel.app/

**Comment by crocmons** [comment]
> Thanks Adrian for the wonderful tutorial. Am having an issue uploading the server files to render. Keep getting an error
> 
> ![image](https://user-images.githubusercontent.com/55574810/209454624-4f2be4b1-83d8-40b9-b904-304d9f3fa614.png)
> 
> see image attached. Any assistance or advice
> 
> git link: https://github.com/Skullomanic84/codex

In render you root directory should be server and build command should be npm install if you are using npm ..then start should be specify on your server package.json file check it there if you using start on the json file then it should be npm start or if you use server then it should be npm run server.. @Skullomanic84

**Comment by Skullomanic84** [comment]
> > Thanks Adrian for the wonderful tutorial. Am having an issue uploading the server files to render. Keep getting an error
> > ![image](https://user-images.githubusercontent.com/55574810/209454624-4f2be4b1-83d8-40b9-b904-304d9f3fa614.png)
> > see image attached. Any assistance or advice
> > git link: https://github.com/Skullomanic84/codex
> 
> @Skullomanic84 **render deploy issue:** In render your root directory should be server and the build command should be npm install if you are using npm ..then start should be specified on your server package.json file check it there if you using start on the JSON file then it should be the npm start or if you use server then it should be npm run server..
> 
> **401 Issue solved / render issue solved:**
> 
> Make sure that your localhost is closed that is not up & running while deploying because it conflicts with your API key with the locally deployed API key. then deploy the server to render.com and add also your environment key in the Environment Variable. Now Update your fetch URL on the client side by adding your back-end render deploy URL then open your terminal and do this thing -- git init git add . git commit -m "fetch URL or something you want" git push That should be updated, your GitHub code . Now go to the vercel select your GitHub repo The root directory should be the client then hit deploy that's all ..
> 
> My code is perfectly working on the live deployment-

thank you worked perfectly

**Comment by Mussassa** [comment]
> > Thanks Adrian for the wonderful tutorial. Am having an issue uploading the server files to render. Keep getting an error
> > ![image](https://user-images.githubusercontent.com/55574810/209454624-4f2be4b1-83d8-40b9-b904-304d9f3fa614.png)
> > see image attached. Any assistance or advice
> > git link: https://github.com/Skullomanic84/codex
> 
> In render you root directory should be server and build command should be npm install if you are using npm ..then start should be specify on your server package.json file check it there if you using start on the json file then it should be npm start or if you use server then it should be npm run server.. @Skullomanic84

Thank you @crocmons, the first solution worked for me :)
