### ISSUE TITLE
POST http://localhost:3000/ 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Sujansinh-thakor** [adrianhajdin/project_openai_codex#50]
## I have changed api key to new api key, moved .env file to server folder and also tried to change port number but still getting this same error.
![image](https://user-images.githubusercontent.com/88817533/230958496-5ea3ea40-cee7-4b5e-bb4a-f2245e85dfe1.png)
![image](https://user-images.githubusercontent.com/88817533/230958628-8c245c91-a1a5-4333-9c7a-daf63777e5fc.png)

![image](https://user-images.githubusercontent.com/88817533/230957216-3ded52ff-187f-4e7b-8eaf-6cf29e0ba3c4.png)
### here is script.js code
![image](https://user-images.githubusercontent.com/88817533/230957418-17310657-f06a-4b62-bb1e-fedc4d9daf63.png)
![image](https://user-images.githubusercontent.com/88817533/230957421-0b018fc9-25f6-4a06-acc7-f368b3416302.png)
### server.js
![image](https://user-images.githubusercontent.com/88817533/230958099-057e9f1c-aa25-4b02-bdbb-3becc00fbd74.png)
![image](https://user-images.githubusercontent.com/88817533/230958130-5654b4bc-2a0a-41e5-890d-3a232ef8aa2c.png)

**Comment by Kritikavig** [comment]
I am also facing the same issue, how you fixed this ?
